css-writing-modes-3/text-combine-upright/reference/horizontal-ahem-1x1-notref.html, css-writing-modes-3/text-combine-upright/reference/horizontal-ahem-1x3-notref.html, css-writing-modes-3/text-combine-upright/reference/horizontal-ahem-1x4-notref.html, css-writing-modes-3/text-combine-upright/reference/horizontal-ahem-1x5-notref.html, css-writing-modes-3/text-combine-upright/reference/vertical-ahem-1x1-ref.html, css-writing-modes-3/text-combine-upright/reference/vertical-ahem-1x3-ref.html, css-writing-modes-3/text-combine-upright/reference/vertical-ahem-1x4-ref.html, css-writing-modes-3/text-combine-upright/reference/vertical-ahem-1x5-ref.html, css-writing-modes-3/text-combine-upright/value-all-002.html, css-writing-modes-3/text-combine-upright/value-all-003.html, css-writing-modes-3/text-combine-upright/value-digits2-002.html, css-writing-modes-3/text-combine-upright/value-digits2-003.html, css-writing-modes-3/text-combine-upright/value-digits3-001.html, css-writing-modes-3/text-combine-upright/value-digits3-002.html, css-writing-modes-3/text-combine-upright/value-digits3-003.html, css-writing-modes-3/text-combine-upright/value-digits4-001.html, css-writing-modes-3/text-combine-upright/value-digits4-002.html, css-writing-modes-3/text-combine-upright/value-digits4-003.html, css-writing-modes-3/text-combine-upright/value-none-001.html
add rendering tests of text-combine-upright that do not requre tailored font.
* value-all-002.html
* value-all-003.html
* value-digits2-002.html
* value-digits2-003.html
* value-digits3-001.html
* value-digits3-002.html
* value-digits3-003.html
* value-digits4-001.html
* value-digits4-002.html
* value-digits4-003.html
* value-none-001.html
* reference/horizontal-ahem-1x1-notref.html
* reference/horizontal-ahem-1x3-notref.html
* reference/horizontal-ahem-1x4-notref.html
* reference/horizontal-ahem-1x5-notref.html
* reference/vertical-ahem-1x1-ref.html
* reference/vertical-ahem-1x3-ref.html
* reference/vertical-ahem-1x4-ref.html
* reference/vertical-ahem-1x5-ref.html
Note that value-all-001.html and value-digits2-001.html are missing: these require a font.
BUG: …
=> CSS Writing Modes: add tests for text-combine-upright

css21/text/text-decoration-065.xht
- The',' between 'does not' and 'blink' will confuse others that the decoration line should display or not, remove the ','
=> Update text-decoration-065 assert description

css-color-3/t422-rgba-clamping-a1.0-b-ref.html, css-color-3/t424-hsl-basic-a-ref.html, css-color-3/t424-hsl-parsing-f-ref.html
- According to color transform website, the render result of hsl(120, 100%, 25%) should be the same as #008000, not green
- Add white background color as origin test setting
=> Update reference files for css color tests

css-writing-modes-3/text-combine-upright/reference/horizontal-ahem-1x1-notref.html, css-writing-modes-3/text-combine-upright/reference/horizontal-ahem-1x3-notref.html, css-writing-modes-3/text-combine-upright/reference/horizontal-ahem-1x4-notref.html, css-writing-modes-3/text-combine-upright/reference/horizontal-ahem-1x5-notref.html, css-writing-modes-3/text-combine-upright/reference/vertical-ahem-1x1-ref.html, css-writing-modes-3/text-combine-upright/reference/vertical-ahem-1x3-ref.html, css-writing-modes-3/text-combine-upright/reference/vertical-ahem-1x4-ref.html, css-writing-modes-3/text-combine-upright/reference/vertical-ahem-1x5-ref.html, css-writing-modes-3/text-combine-upright/reference/writing-mode-horizontal-001l-ref.html, css-writing-modes-3/text-combine-upright/reference/writing-mode-horizontal-001r-ref.html, css-writing-modes-3/text-combine-upright/value-all-002.html, css-writing-modes-3/text-combine-upright/value-all-003.html, css-writing-modes-3/text-combine-upright/value-digits2-002.html, css-writing-modes-3/text-combine-upright/value-digits2-003.html, css-writing-modes-3/text-combine-upright/value-digits3-001.html, css-writing-modes-3/text-combine-upright/value-digits3-002.html, css-writing-modes-3/text-combine-upright/value-digits3-003.html, css-writing-modes-3/text-combine-upright/value-digits4-001.html, css-writing-modes-3/text-combine-upright/value-digits4-002.html, css-writing-modes-3/text-combine-upright/value-digits4-003.html, css-writing-modes-3/text-combine-upright/value-none-001.html, css-writing-modes-3/text-combine-upright/writing-mode-horizontal-001l.html, css-writing-modes-3/text-combine-upright/writing-mode-horizontal-001r.html
I've used 100px for font-size in my TCU tests; however, gtalbot's told me that
may overflow on UAs that support vertical writing modes but logical properties.
http://lists.w3.org/Archives/Public/public-css-testsuite/2015Feb/0028.html
Per his advice, update font-size to 80px so that tests fit in 800x600 dims.
=> Writing Modes: use smaller fonts for text-combine-upright tests

css-grid-1/grid-model/grid-first-line-001.xht, css-grid-1/grid-model/grid-first-line-002.xht, css-grid-1/grid-model/grid-first-line-003.xht, css-grid-1/grid-model/grid-inline-first-line-001.xht, css-grid-1/grid-model/grid-inline-first-line-002.xht, css-grid-1/grid-model/grid-inline-first-line-003.xht
This pull request is part of issue #632 (a similar approach should be followed to test `::first-letter`).
=> [css-grid] first-line does not apply to grid containers

css-grid-1/grid-model/grid-first-letter-001.xht, css-grid-1/grid-model/grid-first-letter-002.xht, css-grid-1/grid-model/grid-first-letter-003.xht, css-grid-1/grid-model/grid-inline-first-letter-001.xht, css-grid-1/grid-model/grid-inline-first-letter-002.xht, css-grid-1/grid-model/grid-inline-first-letter-003.xht, css-grid-1/reference/grid-first-letter-green-margin-no-collapse-ref.xht
This pull request is part of issue #632. It just mimics the tests for `::first-line` done in #699.
=> [css-grid] first-letter does not apply to grid containers

cssom-1/escape.html
This test is based on Mathias Bynens's test at
<https://github.com/mathiasbynens/CSS.escape/blame/master/tests/tests.js>.
@mathiasbynens, can you please confirm you're okay with submitting this test under [the licensing conditions](https://github.com/w3c/csswg-test/blob/master/CONTRIBUTING.md)?
=> Add a test for CSS.escape.

css-ui-3/nav-dir-missing-1.html, css-ui-3/nav-dir-missing-2.html, css-ui-3/nav-dir-missing-3.html, css-ui-3/nav-dir-missing-4.html
This checks that normal spacial navigation works correctly if no element
matches the id selector used in the nav-* properties.
At the time of making this pull request, this requirement is only implied in the TR draft. The normative statement has been added to the editor's draft.
=> Tests for the directional nav-* properties

css-text-3/overflow-wrap-break-word-001.html, css-text-3/reftest/overflow-wrap-break-word-001-ref.html
To be merged if we resolve in favor of https://lists.w3.org/Archives/Public/www-style/2015Jun/0100.html
(and if the test looks sane, of course).
=> [css-text-3] TC for making sure break-word also breaks &nbsp;

css-grid-1/grid-definition/grid-inline-support-grid-template-areas-001.xht, css-grid-1/grid-definition/grid-support-grid-template-areas-001.xht
grid-template-areas can have now dot sequences to represent unnamed areas, added new test cases on the related tests.
Also, the space between named and unnamed areas is not mandatory. Added new cases as this was not being checked before.
This is an update for issue #649.
=> [css-grid] Add new cases for grid-template-areas with dots sequences

css-pseudo-4/first-letter-001-ref.html, css-pseudo-4/first-letter-001.html, css-pseudo-4/first-letter-002.html, css-pseudo-4/first-letter-003.html
Previous levels of CSS gave extra flexibility to User Agents to layout
::first-letter in ways that made sense for Drop Caps. As this did not
work interoperably and better ways to do Drop Caps are being introduced,
this possibility has been disallowed. These tests check that conventional
layout is being applied to the ::first-letter pseudo.
=> Tests for the formatting of ::first-letter

css-writing-modes-3/text-combine-upright/layout-rules-001.html, css-writing-modes-3/text-combine-upright/reference/layout-rules-001-ref.html
The spec (http://dev.w3.org/csswg/css-writing-modes/#text-combine-layout) says:
> The effective size of the composition is assumed to be 1em square; anything
> outside the square is not measured for layout purposes.
To test this tcu-font has a special glyph http://test.csswg.org/source/css-writing-modes-3/test-plan/req-tcu-font.html#glyphs-that-is-larger-than-1em-square
=> Writing Modes: add test for text-combine-upright layout rules

css-writing-modes-3/reference/horizontal-ahem-1x1-notref.html, css-writing-modes-3/reference/horizontal-ahem-1x3-notref.html, css-writing-modes-3/reference/horizontal-ahem-1x4-notref.html, css-writing-modes-3/reference/horizontal-ahem-1x5-notref.html, css-writing-modes-3/reference/vertical-ahem-1x1-ref.html, css-writing-modes-3/reference/vertical-ahem-1x3-ref.html, css-writing-modes-3/reference/vertical-ahem-1x4-ref.html, css-writing-modes-3/reference/vertical-ahem-1x5-ref.html, css-writing-modes-3/reference/writing-mode-horizontal-001l-ref.html, css-writing-modes-3/reference/writing-mode-horizontal-001r-ref.html, css-writing-modes-3/text-combine-upright-value-all-002.html, css-writing-modes-3/text-combine-upright-value-all-003.html, css-writing-modes-3/text-combine-upright-value-digits2-002.html, css-writing-modes-3/text-combine-upright-value-digits2-003.html, css-writing-modes-3/text-combine-upright-value-digits3-001.html, css-writing-modes-3/text-combine-upright-value-digits3-002.html, css-writing-modes-3/text-combine-upright-value-digits3-003.html, css-writing-modes-3/text-combine-upright-value-digits4-001.html, css-writing-modes-3/text-combine-upright-value-digits4-002.html, css-writing-modes-3/text-combine-upright-value-digits4-003.html, css-writing-modes-3/text-combine-upright-value-none-001.html, css-writing-modes-3/writing-mode-horizontal-001l.html, css-writing-modes-3/writing-mode-horizontal-001r.html
Gérard told me that browsers differ on default line-height values.
https://lists.w3.org/Archives/Public/public-css-testsuite/2015Jun/0039.html
The commit includes fix for wording ("rectangles" to "squares") for a few tests.
=> update text-combine-upright tests using Ahem to set line-height explicitly

css-transitions-1/events-007.html
See also http://crbug.com/437860, http://bugzil.la/1182856
=> Add test that transitionend is not fired after element is made display:none

css-transitions-2/transitioncancel-001.html
CC: @dbaron (as Editor of the relevant spec)
=> Test that transitioncancel is fired if element is made display:none during transition

README.md
public-css-testsuite@w3.org isn't currently mentioned in either the README or CONTRIBUTING docs.
This PR corrects this oversight by adds a section to the README mentioning the mailing list, patterned off of [the analogous section of w3c/web-platform-tests' README](https://github.com/w3c/web-platform-tests/blob/master/README.md#getting-involved).
=> README: Mention public-css-testsuite@w3.org

geometry-1/DOMRect-001.html
The spec changed to make the constructor parameters optional, but the test wasn't updated.
=> Bug 29090 - Fix DOMRect constructor tests

css-transforms-1/reference/transform-scale-test-ref.html, css-transforms-1/scale-optional-second-001.html, css-transforms-1/transform-scale-test.html
The two test cases got failed when comparing reference cases on device Google Nexus 4,
it's better to use even pixel than odd pixel.
=> Update two transforms tests with even pixel

css-ui-3/select-cursor-001-manual.html
Refs:
* https://connect.microsoft.com/IE/feedback/details/963961/when-hovering-over-a-select-menu-item-the-cursor-for-the-element-underneath-the-menu-is-displayed
* https://github.com/twbs/bootstrap/issues/14528
=> Add test of `cursor` on element underneath a <select> menu

css-variables-1/css-vars-custom-property-case-sensitive-001.html, css-variables-1/css-vars-custom-property-inheritance.html, css-variables-1/reference/css-vars-custom-property-case-sensitive-ref.html, css-variables-1/test_variable_legal_values.html
Replace `var-foo` and `var(foo)` in tests with `--foo` and `var(--foo)` per spec change.
Rewrite `css-vars-custom-property-case-sensitive-001` to test the case-sensitivity of the property name rather than just of the `var-` prefix, since the new `--` prefix has no case.
r? @Ms2ger
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/847)
=> css-variables-1: Update from var- syntax

css-transforms-1/transform_translate.html, css-transforms-1/transform_translate_invalid.html, css-transforms-1/transform_translate_max.html, css-transforms-1/transform_translate_min.html, css-transforms-1/transform_translate_neg.html, css-transforms-1/transform_translate_second_omited.html, css-transforms-1/transform_translate_zero.html
- The latest W3C spec: http://www.w3.org/TR/cssom/#cssstyledeclaration has removed function getPropertyCSSValue, so use function getPropertyValue to get property value instead.
- CSS Transforms spec: http://www.w3.org/TR/css-transforms-1/#transform-property says the final transformation value for a coordinate system will be converted to in the list to its corresponding matrix.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/822)
=> Update transforms getPropertyCSSValue tests

tools/build.py
The argument to SourceTree is never used. This allows a build to finish in a
git clone of the repository.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/851)
=> Remove the unnecessary dependency on a Mercurial repository in build.py.

.travis.yml, tools/travis/LICENSE, tools/travis/build.py, tools/travis/vcs.py
This will also push the built test suites to <https://github.com/jgraham/css-test-built>, allowing browsers to pull them in easily. (Servo already uses this repository.)
In the future, I hope to make Travis detect build warnings, for example when I forget to add a reference file.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/854)
=> Run the build on Travis.

filters-1/fecolormatrix-type.html
Replaces broken http://www.w3.org/TR/filter-effects-1/#feColorMatrixTypeAttribute link with working http://www.w3.org/TR/filter-effects-1/#element-attrdef-fecolormatrix-type link.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/867)
=> [filters-1][filter-effects] Fix broken #feColorMatrixTypeAttribute rel="help" anchor

css-regions-1/flow-content-001.xht, css-regions-1/flow-content-002.xht, css-regions-1/flow-into-parsing-001.html, css-regions-1/interactivity/resizing/regions-resizing-001.html, css-regions-1/interactivity/resizing/regions-resizing-002.html, css-regions-1/interactivity/resizing/regions-resizing-003.html, css-regions-1/interactivity/resizing/regions-resizing-004.html, css-regions-1/interactivity/resizing/regions-resizing-005.html, css-regions-1/interactivity/resizing/regions-resizing-006.html, css-regions-1/interactivity/resizing/regions-resizing-007.html, css-regions-1/interactivity/resizing/regions-resizing-008.html, css-regions-1/interactivity/resizing/regions-resizing-009.html, css-regions-1/interactivity/resizing/regions-resizing-010.html, css-regions-1/interactivity/resizing/regions-resizing-011.html, css-regions-1/interactivity/resizing/regions-resizing-012.html, css-regions-1/interactivity/resizing/regions-resizing-013.html, css-regions-1/region-fragment-001.xht, css-regions-1/region-fragment-002.xht
Replaces broken http://www.w3.org/TR/css3-regions/#flow-into links with working http://www.w3.org/TR/css3-regions/#the-flow-into-property links.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/866)
=> [css-regions-1] Fix broken #flow-into rel="help" anchors

css-regions-1/flexbox/autoheight-regions-in-autoheight-flexbox-003.html
Replaces broken http://www.w3.org/TR/css3-regions/#break-after link with working http://www.w3.org/TR/css3-regions/#propdef-break-after link.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/865)
=> [css-regions-1] Fix broken #break-after rel="help" anchor

css21/visuren/left-offset-position-fixed-001.xht
Erratum from #813. The datestamp didn't make it into the 2nd file.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/864)
=> css21/visuren/left-offset-position-fixed-001.xht: Add missing review datestamp

css-flexbox-1/flexbox_rtl-direction.html, css-flexbox-1/flexbox_rtl-order.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column-reverse-nowrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column-reverse-wrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column-reverse.html
Replaces broken http://www.w3.org/TR/css-flexbox-1/#valuedef-column-reverse links with working http://www.w3.org/TR/css-flexbox-1/#valdef-flex-direction-column-reverse links.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/868)
=> [css-flexbox-1] Fix broken #valuedef-column-reverse rel="help" anchors

css-flexbox-1/flexbox_rtl-flow-reverse.html, css-flexbox-1/flexbox_rtl-flow.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column-nowrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column-wrap-reverse.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column-wrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column.html
Replaces broken http://www.w3.org/TR/css-flexbox-1/#valuedef-column links with working http://www.w3.org/TR/css-flexbox-1/#valdef-flex-direction-column links
The fixes the "Test links to unknown specification anchor: http://www.w3.org/TR/css-flexbox-1/#valuedef-column" warnings in the Travis build.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/863)
=> [css-flexbox-1] Fix broken #valuedef-column rel="help" anchors

css-flexbox-1/flexbox_rtl-flow-reverse.html, css-flexbox-1/flexbox_rtl-flow.html, css-flexbox-1/flexbox_rtl-order.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column-nowrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column-reverse-nowrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column-reverse-wrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column-wrap-reverse.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-column-wrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-nowrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-row-nowrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-row-reverse-nowrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-row-reverse-wrap-reverse.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-row-reverse-wrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-row-reverse.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-row-wrap-reverse.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-row-wrap.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-row.html, css-flexbox-1/getcomputedstyle/flexbox_computedstyle_flex-flow-wrap.html, css-flexbox-1/ttwf-reftest-flex-inline.html
Fixes various `Test links to unknown specification anchor:` warnings in the Travis build.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/899)
=> [css-flexbox-1] Fix broken rel="help" anchors

css-flexbox-1/css-box-justify-content.html, css-flexbox-1/reference/css-box-justify-content-ref.html
- text-align must be left inside the inner boxes, because
we only want to use text-align to align the boxes themselves,
we don't want to change the contents
- Use nbsp instead of margin-left for spacing to ensure the same
width as the spaces in the reference rendering
=> [css-flexbox] Fix the css-box-justify-content testcase

css-flexbox-1/reference/flex-align-items-center-ref.html
The position calculations in the reference were incorrect.  I have manually
verified that my new positioning is correct, and it also matches browser
rendering (tested in Chrome and Firefox nightlies)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/878)
=> [css-flexbox] fix flex-align-items-center-ref.html

css-flexbox-1/reference/flex-flexitem-percentage-prescation-ref.html
In truth I don't understand this test, or why its <title> is what it is,
but at least this makes the reference match the testcase. I can only assume
that it was written before fractional pixels were common?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/879)
=> [css-flexbox] Fix flex-flexitem-percentage-prescation-ref.html

css-flexbox-1/reference/ttwf-reftest-flex-order-ref.html
Remove spaces between <span>s, because they mess up the rendering.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/880)
=> [css-flexbox] fix ttwf-reftest-flex-order-ref.html

css-flexbox-1/flexbox_order-noninteger-invalid.html
As this test uses an empty reference, it needs to use a white background
for this box.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/882)
=> [css-flexbox] Fix flexbox_order-noninteger-invalid.html

css-flexbox-1/reference/ttwf-reftest-flex-direction-row-reverse-ref.html, css-flexbox-1/ttwf-reftest-flex-direction-row-reverse.html
The reference should not use flexbox itself. It also was for some reason
not right-aligned. This change fixes that, and also a typo.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/885)
=> [css-flexbox] Fix ttwf-reftest-flex-direction-row-reverse.html

css-flexbox-1/css-flexbox-row-ref.html, css-flexbox-1/css-flexbox-row-reverse-wrap-reverse.html, css-flexbox-1/css-flexbox-row-reverse-wrap.html, css-flexbox-1/css-flexbox-row-reverse.html, css-flexbox-1/css-flexbox-row-wrap-reverse.html, css-flexbox-1/css-flexbox-row-wrap.html, css-flexbox-1/css-flexbox-row.html
The test was implicitly assuming that each line is 1.5em high.  Make that
explicit by setting line-height: 1.5em in the reference + tests.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/888)
=> [css-flexbox] Fix css-flexbox-row-*

css-ui-3/text-overflow.html, css-ui-3/zcorpan/box-sizing-padding-box-block-001.html, css-ui-3/zcorpan/guide.txt
Fixes a few `Test links to unknown specification anchor:` warnings in the Travis build.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/906)
=> [css-ui-3] Fix broken rel="help" anchors

css-flexbox-1/css-flexbox-img-expand-evenly.html, css-flexbox-1/reference/css-flexbox-img-expand-evenly-ref.html
- Path to the image file was incorrect
- Linebreak needs to be removed, see comment in patch
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/877)
=> [css-flexbox] fix css-flexbox-img-expand-evenly.html

css-flexbox-1/flex-lines/multi-line-wrap-reverse-column-reverse-ref.html, css-flexbox-1/flex-lines/multi-line-wrap-with-column-reverse-ref.html
The 33.3% width needs a higher precision to look correct, at least on Chrome.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/900)
=> [css-flexbox-1] Fix flex-lines tests

css-flexbox-1/reference/flex-items-flexibility.html
The math was wrong in this testcase. In addition, I have cleaned up this
testcase not to rely on display: flex itself, and removed unnecessary elements.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/901)
=> [css-flexbox-1] Fix reference for flex-items-flexibility.html

css-flexbox-1/flexbox_flex-natural-mixed-basis-auto.html
The reference uses a width of 35em, whereas the test case used 35ex.
Make them both use 35em.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/902)
=> [css-flexbox-1] Fix flexbox_flex-natural-mixed-basis-auto.html

cssom-1/css-style-declaration-modifications.html, cssom-1/cssimportrule.html, cssom-1/cssstylerule.html, cssom-1/index-003.html, cssom-1/style-sheet-interfaces-001.html, cssom-1/ttwf-cssom-doc-ext-load-count.html, cssom-1/ttwf-cssom-doc-ext-load-tree-order.html, cssom-1/ttwf-cssom-document-extension.html
Fixes a few `Test links to unknown specification anchor: warnings` in the Travis build.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/907)
=> [cssom-1] Fix broken rel="help" anchors

css-flexbox-1/css-flexbox-column-reverse-wrap-reverse.html, css-flexbox-1/css-flexbox-column-wrap-reverse.html
These need to be aligned flex-end, not flex-start, to match the reference --
this is because wrap-reverse swaps the cross-start and the cross-end edges.
https://drafts.csswg.org/css-flexbox/#valdef-flex-wrap-wrap-reverse
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/904)
=> [css-flexbox-1] Fix css-flexbox-column-{reverse-,}wrap-reverse.html

tools/travis/build.py
Return `[]` instead of `['']` as the list of new commits in said case.
Refs:
* https://github.com/w3c/csswg-test/pull/908#issuecomment-147879105
* https://travis-ci.org/w3c/csswg-test/builds/85227540
CC: @jgraham
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/918)
=> Fix tools/travis/build.py:get_new_commits() when there aren't any new commits

mediaqueries-3/min-width-tables-001.html, mediaqueries-3/support/min-width-tables-001-iframe.html
Refs http://wkbug.com/138167, https://github.com/twbs/bootstrap/issues/9774
I tried to avoid using `<iframe>` in the reference file, but browsers seem to apply an inconsistent magic bottom margin to the testcase `<iframe>`, so I couldn't get the `<p>`'s vertical position to match consistently.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/812)
=> [CSS22][css-tables][mediaqueries][css3-mediaqueries] Add test of table layout after resizing viewport

css21/backgrounds/background-root-102.xht, css21/backgrounds/background-root-103.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/951)
=> Use reftest-wait to ensure background-root-102.xht and background-root-103.xht do not finish early.

css-grid-1/grid-definition/grid-inline-support-flexible-lengths-001.xht, css-grid-1/grid-definition/grid-support-flexible-lengths-001.xht
The spec now says (http://www.w3.org/TR/css-grid-1/#flex-factor-sum):
"Let flex factor sum be the sum of the flex factors of the flexible
tracks. If this value is less than 1, set it to 1 instead."
This means that flexible tracks under 1fr will have a special behavior.
Updated the tests to follow this new behavior.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/953)
=> [css-grid] Fix test for flexible lengths under 1

css-grid-1/grid-definition/grid-inline-support-grid-template-areas-001.xht, css-grid-1/grid-definition/grid-support-grid-template-areas-001.xht
We have a case for a wrong value "," that was not being checked properly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/954)
=> [css-grid] Fix wrong value in grid-template-areas tests

css-grid-1/grid-items/grid-inline-items-001.xht, css-grid-1/grid-items/grid-inline-items-002.xht
Some space were added due to the break in the tests using inline grids.
Change the tests to avoid the break and fix the issue.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/955)
=> [css-grid] Fix inline grid tests to avoid weird spaces

cssom-1/css-style-declaration-modifications.html, cssom-1/cssimportrule.html
This removes incorrect assertions (IDL attributes do not correspond to 'own'
properties), tightens serialization requirements (to match the specification
and both Gecko and Chrome), and removes some unnecessary cruft.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/962)
=> Improve CSSOM tests.

geometry-1/DOMQuad-001.html
This makes the test useful for an implementation without support for the
'bounds' attribute.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/967)
=> Split up tests in DOMQuad-001.html.

css-text-3/white-space/seg-break-transformation-000.html, css-text-3/white-space/seg-break-transformation-001.html, css-text-3/white-space/seg-break-transformation-002.html, css-text-3/white-space/seg-break-transformation-003.html, css-text-3/white-space/seg-break-transformation-004.html, css-text-3/white-space/seg-break-transformation-005.html, css-text-3/white-space/seg-break-transformation-006.html, css-text-3/white-space/seg-break-transformation-007.html, css-text-3/white-space/seg-break-transformation-008.html, css-text-3/white-space/seg-break-transformation-009.html, css-text-3/white-space/seg-break-transformation-010.html, css-text-3/white-space/seg-break-transformation-011.html, css-text-3/white-space/seg-break-transformation-012.html, css-text-3/white-space/seg-break-transformation-014.html, css-text-3/white-space/seg-break-transformation-015.html, css-text-3/white-space/seg-break-transformation-016.html, css-text-3/white-space/seg-break-transformation-017.html, css-text-3/white-space/white-space-collapse-002.html
I believe [the recent "Remove trailing whitespace" commit](https://github.com/w3c/csswg-test/commit/55a44121247a4c94e9af8e08640617312cce625d) broke tests for that white space.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/979)
=> Revert "Remove trailing whitespace" for white-space tests

geometry-1/DOMPoint-001.html
Note that there are still a large number of bugs remaining in this tests,
like testing constructor overloads that take dictionaries that no longer
exist in the specification.
Fixes #968.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/969)
=> Move the DOMPoint test a little closer to the specification.

css-flexbox-1/ttwf-reftest-flex-wrap-reverse.html, css-flexbox-1/ttwf-reftest-flex-wrap.html
For some reason, these tests passed on Linux for me but not on Windows.
At any rate, an explicit height is the right solution.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/984)
=> [css-flexbox] Give the container an explicit height

css-grid-1/grid-items/grid-item-containing-block-001.html, css-grid-1/grid-items/grid-item-containing-block-001.xht
According to https://www.w3.org/TR/css-grid-1/#grid-items
> A grid item is sized within the containing block defined by its grid area similarly to an equivalent block-level box in an equivalently-sized containing block, except that auto margins and the box alignment properties have special effects.
I think it's worth testing it regardless of `fr` unit, so it would be easier to isolate an issue.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1012)
=> [css-grid] Add test for grid item sizing within its grid area

.hgsubstate, tools/travis/build.py
This is soon to be important as I do major rewrites of them.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1017)
=> Make the travis builder get the right revision of the hg submodules

selectors-4/focus-within-shadow-003.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1023)
=> [css-selectors] Fix typo in ref filename

cssom-view-1/elementFromPosition.html, cssom-view-1/ttwf-js-cssomview-getclientrects-length.html
```
Test links to unknown specification anchor: http://www.w3.org/TR/cssom-view/#widl-Document-elementFromPoint-Element-float-x-float-y
in: cssom-view-1/elementFromPosition.html
Test links to unknown specification anchor: http://www.w3.org/TR/cssom-view/#the-getclientrects-and-getboundingclientrect-methods
in: cssom-view-1/ttwf-js-cssomview-getclientrects-length.html
```
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1026)
=> [cssom-view-1] Fix outdated/broken spec anchors

cssom-1/serialize-namespaced-type-selectors.html
Tests for expected serialization of various combinations of type /
universal selectors, namespace prefixes, and presence of default
namespaces.
All tests pass in Firefox 43. There are patches in review to make them
all pass in Blink.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1020)
=> [cssom] Serialize namespaced type selectors.

css-grid-1/grid-items/grid-item-containing-block-002.html, css-grid-1/grid-items/grid-item-containing-block-003.html, css-grid-1/grid-items/grid-item-containing-block-004.html
More tests for grid item sizing started at https://github.com/w3c/csswg-test/pull/1012
- track sizes in `%`
- track sizes in `fr`
- track sizes in `fr`, within `absolute` positioned grid 
@mrego, I'm not sure whether last one fits here, maybe it should go to tests for flex size calculation, or even for more complex, non-direct-spec tests folder?
I thought, it would be nice to have it, as current Chrome stable failed on it (IE, Firefox, and Canary passes it)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1019)
=> [css-grid] Add more tests for grid item containing block

css-shapes-1/shape-outside/shape-image/gradients/shape-outside-radial-gradient-001.html
The reference was removed in 02346b92b1f21a182dea5e2e2ded3c8c22112371.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1056)
=> Remove link to removed reference.

geometry-1/DOMMatrix-001.html
- You can't always compare `is2D` against a reference matrix. The value can never be set to `false` once it has been set to `true`, and it will be `true` when the constructor is given 16 arguments.
- One of the test fixtures was marked with `isIdentity=true` when it is not an identity matrix.
- When 6 values are provided, the constructor should NOT throw a TypeError. 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1060)
=> Fixed DOMMatrix tests that were not according to spec

geometry-1/DOMMatrix-003.htm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1066)
=> DOMMatrix: Tests for basic non-mutating methods

css-scoping-1/css-scoping-shadow-assigned-node-with-before-after.html, css-scoping-1/css-scoping-shadow-assigned-node-with-rules.html, css-scoping-1/css-scoping-shadow-host-functional-rule.html, css-scoping-1/css-scoping-shadow-host-rule.html, css-scoping-1/css-scoping-shadow-host-with-before-after.html, css-scoping-1/css-scoping-shadow-invisible-slot.html, css-scoping-1/css-scoping-shadow-root-hides-children.html, css-scoping-1/css-scoping-shadow-slot-display-override.html, css-scoping-1/css-scoping-shadow-slot-fallback.html, css-scoping-1/css-scoping-shadow-slot.html, css-scoping-1/css-scoping-shadow-slotted-nested.html, css-scoping-1/css-scoping-shadow-slotted-rule.html, css-scoping-1/css-scoping-shadow-with-outside-rules.html, css-scoping-1/css-scoping-shadow-with-rules-no-style-leak.html, css-scoping-1/css-scoping-shadow-with-rules.html, css-scoping-1/reference/green-box.html
Import tests for https://drafts.csswg.org/css-scoping/#shadow-dom
from http://trac.webkit.org/browser/trunk/LayoutTests/fast/shadow-dom
Both WebKit nightly builds and Google Chrome Canary pass all these tests
except css-scoping-shadow-slot-display-override.html which fails on Chrome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1084)
=> Add shadow boundary tests for CSS Scoping Level 1

css-scoping-1/shadow-cascade-order-001.html
This was originally put in wpt/shadow-dom/styles/, but should be in
css-scoping-1 tests.
On moving the file, I also edited the meta help link to the latest
spec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1085)
=> Move shadow DOM cascading order test from WPT

css-scoping-1/css-scoping-shadow-slot-style.html
This test passes on WebKit nightly builds and fails on Google Chrome Canary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1087)
=> Add a test for inheriting style from a slot element to the slotted content

tools/travis/build.py
w3ctestlib depends on private APIs that were removed in later versions.
gsnedders is working to rectify that, but right now this is the safest way
back to working travis builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1099)
=> Pin html5lib to 0.9999999 for now.

css-display-3/display-contents-computed-style.html
All tests pass in the Gecko implementation. The #t5 test relies on https://github.com/w3c/csswg-drafts/issues/482 being resolved as proposed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1126)
=> Computed style tests for display:contents.

css-syntax-3/ident-three-code-points.html
Based on a discussion with @tabatkins I have created a new testcase for determining if an ID is a valid id after 3 codepoints. This will replace (although I didn't delete it) ident-20.xht in CSS 2. I have placed this within the L3 folder as we have done in other modules even though there are only tests for charset currently within the module. Based on the spec, I believe this is correct but Firefox/Chrome currently allow `---` to be a valid ident even though the current spec text only allows two of them (assuming I'm reading it correctly).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1134)
=> [css-syntax] Added test for three code points for an ident

css-variables-1/reference/variable-reference-without-whitespace-ref.html, css-variables-1/variable-reference-without-whitespace.html
Firefox represents custom property values as strings internally, and inserts `/**/` between adjacent tokens that would otherwise be re-parsed as a single token.
It relies on the [table](https://drafts.csswg.org/css-syntax/#serialization) in the css-syntax spec, but that table has not been updated when the definition of identifier tokens was [extended](http://hg.csswg.org/drafts/rev/ab8b75f1fa88) to allow `--` prefixes. This was just [fixed](http://hg.csswg.org/drafts/rev/92d088e07ca2).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/852)
=> Add a css-variables test that Firefox fails.

css21/pagination/widows-004a.xht
Texts in the test seem to be incorrect.
Since the used value of widows is 5, the last 5 lines should go to the second page.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1006)
=> Fix css21/pagination/widows-004a

tools/travis/build.py
This gives us a bit more debug information for #1140, and stops Travis from constantly timing out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1141)
=> Output changesets to build, refuse to build more than 50

css21/visufx/overflow-009.html
Not quite sure which spec's test suite this should go under. css-overflow doesn't yet have a test suite, but `vh` isn't part of CSS2 FWICT. Happy to substitute the `vh` usages for something else if someone has a suggestion.
Refs https://bugs.webkit.org/show_bug.cgi?id=153852
Refs https://github.com/twbs/bootstrap/issues/14839
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1079)
=> [CSS22][css-overflow] Test that position:fixed element doesn't trump body{overflow:hidden}

css-display-3/display-contents-before-after-002.html, css-display-3/display-contents-block-001.html, css-display-3/display-contents-first-line-001.html, css-display-3/display-contents-inline-001.html, css-display-3/display-contents-pass-green-no-red-ref.html, css-display-3/display-contents-pass-no-red-ref.html, css-display-3/display-contents-pass-ref.html, css-display-3/display-contents-tr-001.html
Several of the display:contents tests exercised a text shaping bug in
Blink where "PASS" would be rendered differently from
"P<span>ASS</span>". Adjust tests and references to split the text the
same way across tests and references. We are testing display:contents,
not text shaping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1143)
=> [css-display-3] Make contents tests independent of text-shaping.

css-display-3/display-contents-tr-001-ref.html, css-display-3/display-contents-tr-001.html
r? @rune-opera 
(Kept you as the author, it's intentional)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1146)
=> [css-display-3] Add a explicit reference for display-contents-tr-001.html to avoid text shaping bugs in Blink.

css-ui-3/caret-color-009.html
It was referencing twice "d1" when the second time it should use "d2".
Please @frivoal take a look. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1147)
=> [css-ui] Fix mistake on caret-color-009.html test

css-ui-3/caret-color-002.html
The text talks about 2 textareas, but there's only 1.
Please @frivoal take a look.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1149)
=> [css-ui] Fix mistake on caret-color-002.html test

css-ui-3/caret-color-001.html, css-ui-3/caret-color-002.html, css-ui-3/caret-color-003.html, css-ui-3/caret-color-004.html, css-ui-3/caret-color-005.html, css-ui-3/caret-color-006.html, css-ui-3/caret-color-007.html, css-ui-3/caret-color-008.html
This makes easier to see the caret as lime is used over a black background.
I believe it's easier to see lime over black than green over black.
What do you think @frivoal ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1150)
=> [css-ui] Use bigger font and lime color for caret-color tests

cssom-1/cssom-cssText-serialize.html
According to https://drafts.csswg.org/cssom/#serialize-a-css-declaration there's an unconditional semicolon.
This test currently fails in both Chrome and Firefox because of the missing semicolon.
r? @zcorpan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1154)
=> Fix cssom-cssText-serialize.html

mediaqueries-3/reference/ref-green-body.xht, mediaqueries-3/relative-units-001.html, mediaqueries-3/relative-units-002.html, mediaqueries-3/relative-units-003.html, mediaqueries-3/relative-units-004.html
Refs https://drafts.csswg.org/mediaqueries/#units
Refs https://bugs.webkit.org/show_bug.cgi?id=156684
Refs http://zellwk.com/blog/media-query-units/#1-font-size-changed-in-html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1080)
=> [mediaqueries] Test that e.g. (min-width:100rem) isn't affected by html{font-size:200%;}

css-ui-3/caret-color-019.html, css-ui-3/caret-color-020.html
Added 2 new tests to check that "caret-color: auto" isn't interpolatible,
but "caret-color: currentcolor" is.
See w3c/csswg-drafts#781 for more information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1162)
=> [css-ui] Verify caret-color animations

css-fonts-3/test-synthetic-italic.xht
This was introduced in cb0aa483996c75c6f4a8dc1c08a1e3a78d996e01.
@svgeesus introduced this trailing whitespace by mistake, and it's causing Tavis failures (e.g. https://travis-ci.org/w3c/csswg-test/jobs/185842710).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1164)
=> [css-fonts-3] Fix trailing whitespace in test-synthetic-italic.xht

css-ui-3/caret-color-019.html, css-ui-3/caret-color-020.html, css-ui-3/caret-color-021.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1166)
=> [css-ui] Fix typo in some caret-color tests

css-transitions-1/transition-timing-function-001.html
According to spec, if the point at which the value changes is `end`, `transition-timing-function` should be  serialized as steps(\<integer\>). But tests don't reflect that.
Spec link: https://drafts.csswg.org/css-transitions/#serializing-a-timing-function
cc @Manishearth 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1168)
=> Remove `end` keyword from transition-timing-function serialization

css-ui-3/caret-color-001.html, css-ui-3/caret-color-002.html, css-ui-3/caret-color-003.html, css-ui-3/caret-color-004.html, css-ui-3/caret-color-005.html, css-ui-3/caret-color-006.html, css-ui-3/caret-color-007.html, css-ui-3/caret-color-008.html, css-ui-3/caret-color-010.html, css-ui-3/caret-color-012.html
This change is needed for [running the tests on Blink](https://codereview.chromium.org/2605173002/). Main reason is that, in this Blink CL, the focusing step is performed after Document load and that's causing differences on the text expectations.
This is particular to Blink implementation, but using the proposed solution would solve it and it doesn't seem harmful (as we're not actually testing `autofocus` on these tests). It'd help to keep `csswg-tests` and Blink tests synchronized.
What do you think?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1169)
=> [css-ui] Avoid autofocus on caret-color tests

tools/build.py, tools/travis/build.py
Currently the build is failing and hanging in pdb. This is bad. All the other `ERROR` messages exit, so this should too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1175)
=> Travis should exit cleanly

css-text-3/word-break/word-break-normal-zh-000.html
The test had a different character in the reference case (語 instead of 話), and should have caused all browsers to fail this test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1178)
=> Fix word-break-normal-zh-000.html

css-flexbox-1/layout-algorithm_algo-cross-line-001.html, css-flexbox-1/layout-algorithm_algo-cross-line-002.html, css-flexbox-1/reference/layout-algorithm_algo-cross-line-001-ref.html, css-flexbox-1/reference/layout-algorithm_algo-cross-line-002-ref.html
According to [9.4. Cross Size Determination #8](https://www.w3.org/TR/css-flexbox-1/#algo-cross-line)
> If the flex container is single-line and has a definite cross size, the cross size of the flex line is the flex container’s inner cross size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1171)
=> [flexbox-1] Test cross-size determination if flex item has overflow: scroll

css-ui-3/caret-color-003.html, css-ui-3/cursor-box-006.html, css-ui-3/text-overflow-005.html
These are a few problems with the css-ui tests that have slipped through earlier reviews.
I am not looking for reviews on this patch as **this** is the result of a review to fix existing problems. I'll merge this myself as soon as travis & co give me the green light.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1182)
=> Css ui test fixes

css-values-3/ch-unit-001.html, css-values-3/ch-unit-002.html, css-values-3/ch-unit-003.html, css-values-3/ch-unit-004.html, css-values-3/reference/ch-unit-001-ref.html, css-values-3/reference/ch-unit-002-ref.html, css-values-4/ic-unit-001.html, css-values-4/ic-unit-002.html, css-values-4/ic-unit-003.html, css-values-4/ic-unit-004.html, css-values-4/reference/ic-unit-001-ref.html, css-values-4/reference/ic-unit-002-ref.html
Adds a vertical variant of the existing test  for the `ch` unit, and both a horiztonal and a vertical equivalent for the `ic` unit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1136)
=> Glyph metric units

lint, lint.whitelist
Also add a bunch of whitelists for SUPPORT-WRONG-DIR now we have it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1184)
=> Update wpt_tools to introduce the new CSS-mode lint

css-text-3/word-break/word-break-normal-zh-000.html
I attempted a change in #1178 but realized that the reference test case used 語 instead of 話. This PR reverts that change and ensures that the characters in the test and ref are both the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1188)
=> Match word-break-normal-zh-000.html characters with reference

css-ui-3/caret-color-015.html, css-ui-3/caret-color-016.html
The tests worked fine when running the tests as is, but the build system
causes their filename to change and they become unusable after that.
Closes #1181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1183)
=> [css-ui-3] Fix glitch in 2 caret-color tests

css-ui-3/support/cursors/.htaccess
[This previous patch](https://github.com/w3c/csswg-test/pull/1187) to fix this TC [did not work](https://lists.w3.org/Archives/Public/public-css-testsuite/2017Jan/0016.html). @plinss [explained](https://lists.w3.org/Archives/Public/public-css-testsuite/2017Jan/0017.html) that with the current server we need to do it using .htaccess instead of .headers files, so this patch does that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1191)
=> [css-ui-3] Fix HTTP headers

css-grid-1/grid-definition/grid-inline-support-flexible-lengths-001.xht, css-grid-1/grid-definition/grid-inline-support-grid-template-columns-rows-001.xht, css-grid-1/grid-definition/grid-inline-support-named-grid-lines-001.xht, css-grid-1/grid-definition/grid-inline-support-repeat-001.xht, css-grid-1/grid-definition/grid-inline-template-columns-rows-resolved-values-001.xht, css-grid-1/grid-definition/grid-support-flexible-lengths-001.xht, css-grid-1/grid-definition/grid-support-grid-template-columns-rows-001.xht, css-grid-1/grid-definition/grid-support-named-grid-lines-001.xht, css-grid-1/grid-definition/grid-support-repeat-001.xht, css-grid-1/grid-definition/grid-template-columns-rows-resolved-values-001.xht, css-grid-1/grid-items/grid-items-001.xht, css-grid-1/grid-items/grid-items-002.xht, css-grid-1/grid-items/grid-order-property-auto-placement-001.xht, css-grid-1/grid-items/grid-order-property-auto-placement-002.xht, css-grid-1/grid-items/grid-order-property-auto-placement-003.xht, css-grid-1/grid-items/grid-order-property-auto-placement-004.xht, css-grid-1/grid-items/grid-order-property-auto-placement-005.xht, css-grid-1/grid-layout-properties.html, css-grid-1/implicit-grids/grid-support-grid-auto-columns-rows-001.html
This is a commit with changes in several tests to update them
to the last changes on the spec.
The changes can be summarized in:
* Use "justify|align-content: start" to avoid the stretch by default.
* Change order of rows and columns in grid-template shorthand.
* "fr" unit is now invalid as minimum track sizing function.
* Fix mistake on grid-support-grid-auto-columns-rows-001.html:
It was defining a class "first-and-second-columns-second-row"
but using a non existent one called "third-column".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1194)
=> [css-grid] Update Grid Layout test suite

css-grid-1/grid-items/grid-minimum-size-grid-items-001.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-002.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-003.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-004.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-005.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-006.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-007.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-008.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-009.xht
Once that issue w3c/csswg-drafts#283 has been solved, this patch
is updating the current tests related to "Implied Minimum Size
of Grid Items" section:
https://drafts.csswg.org/css-grid/#min-size-auto
Please @javifernandez and @svillar take a look to the changes, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1198)
=> [css-grid] Update implied minimum size of grid items tests

css-grid-1/grid-items/grid-minimum-size-grid-items-010.html, css-grid-1/grid-items/grid-minimum-size-grid-items-011.html, css-grid-1/grid-items/grid-minimum-size-grid-items-012.html, css-grid-1/grid-items/grid-minimum-size-grid-items-013.html, css-grid-1/grid-items/grid-minimum-size-grid-items-014.html, css-grid-1/grid-items/grid-minimum-size-grid-items-015.html, css-grid-1/grid-items/grid-minimum-size-grid-items-016.html, css-grid-1/grid-items/grid-minimum-size-grid-items-017.html, css-grid-1/grid-items/grid-minimum-size-grid-items-018.html
This adds more coverage for that spec section:
https://drafts.csswg.org/css-grid/#min-size-auto
The examples in the tests were discussed in w3c/csswg-drafts#283.
Please @javifernandez or @svillar take a look. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1199)
=> [css-grid] Add more tests for Implied Minimum Size of Grid Items section

.gitignore, lint.whitelist, server.js
`server.js` is neither used nor mentioned in any documents, so I suggest removing `server.js`.
If `server.js` is WIP, please revise documentation to include `server.js` usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1203)
=> Remove unused server.js

css-grid-1/grid-items/grid-minimum-size-grid-items-005.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-006.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-007.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-008.xht, css-grid-1/grid-items/grid-minimum-size-grid-items-009.xht, css-grid-1/grid-items/ref-filled-green-100px-square-image.html
We have issues comparing a green image with a green box from HTML/CSS,
using images in the reference files solves the problem.
Check comments on #1202 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1204)
=> [css-grid] Use image in the reference for tests that show an image

css-display-3/display-contents-alignment-001-ref.html, css-display-3/display-contents-alignment-001.html, css-display-3/display-contents-alignment-002-ref.html, css-display-3/display-contents-alignment-002.html, css-display-3/display-contents-computed-style.html
The flex spec was updated a while ago to use the following language for
align-items:
> align-items sets the default alignment for all of the flex container’s items,
> including anonymous flex items. align-self allows this default alignment to
> be overridden for individual flex items.
After that, the CSSWG resolved that align-self: auto computes to itself (see [1] and [2]).
Thus, this test is invalid.
[1]: https://github.com/w3c/csswg-drafts/issues/440#issuecomment-247595259
[2]: https://lists.w3.org/Archives/Public/www-style/2016Sep/0041.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1209)
=> [css-display-3] Remove outdated display: contents test.

css-grid-1/grid-items/grid-items-sizing-alignment-001.html
A mistake in the last pull request #1219.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1224)
=> [css-grid] Fix path to reference file in grid-items/grid-items-sizing-alignment-001.html

lint.whitelist
Again related to my previous PRs #1219 & #1224, sorry for the noise :disappointed:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1226)
=> [css-grid] Remove grid-items/grid-items-sizing-alignment-001.html from lint.whitelist

css-display-3/display-contents-before-after-002.html
Gecko seemingly passed this test, but used inline instead of contents
as the display type. Add a red border to make sure it's really
display:contents.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1230)
=> [css-display-3] Added red border to pseudo elements to avoid false pass.

css-align-3/content-distribution/place-content-shorthand-001.html, css-align-3/content-distribution/place-content-shorthand-002.html, css-align-3/content-distribution/place-content-shorthand-003.html, css-align-3/content-distribution/place-content-shorthand-004.html, css-align-3/content-distribution/place-content-shorthand-005.html, css-align-3/resources/alignment-parsing-utils.js
Added several tests to verify that the 'place-content' shorthand is parsed correctly and it sets the corresponding longhand's values.
Please @mrego and @svillar could you take a look ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1228)
=> [css-align] Added tests to check the 'place-content' shorthand.

css-align-3/default-alignment/place-items-shorthand-001.html, css-align-3/default-alignment/place-items-shorthand-002.html, css-align-3/default-alignment/place-items-shorthand-003.html, css-align-3/default-alignment/place-items-shorthand-004.html, css-align-3/default-alignment/place-items-shorthand-005.html, css-align-3/default-alignment/place-items-shorthand-006.html, css-align-3/resources/alignment-parsing-utils.js
Added several tests to verify that the 'place-items' shorthand is parsed correctly and it sets the corresponding longhand's values.
Please @mrego and @svillar could you take a look ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1231)
=> [css-align] Added tests to verify the parsing of the place-items shorthand.

css-align-3/resources/alignment-parsing-utils.js, css-align-3/self-alignment/place-self-shorthand-001.html, css-align-3/self-alignment/place-self-shorthand-002.html, css-align-3/self-alignment/place-self-shorthand-003.html, css-align-3/self-alignment/place-self-shorthand-004.html, css-align-3/self-alignment/place-self-shorthand-005.html, css-align-3/self-alignment/place-self-shorthand-006.html
Added several tests to verify that the 'place-self' shorthand is parsed correctly and it sets the corresponding longhand's values.
Please @mrego and @svillar could you take a look ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1232)
=> [css-align] Added tests to verify the parsing of the place-self shorthand.

css-align-3/content-distribution/place-content-shorthand-001.html, css-align-3/content-distribution/place-content-shorthand-003.html, css-align-3/content-distribution/place-content-shorthand-004.html, css-align-3/content-distribution/place-content-shorthand-005.html, css-align-3/content-distribution/place-content-shorthand-006.html, css-align-3/default-alignment/place-items-shorthand-001.html, css-align-3/default-alignment/place-items-shorthand-002.html, css-align-3/default-alignment/place-items-shorthand-003.html, css-align-3/default-alignment/place-items-shorthand-004.html, css-align-3/default-alignment/place-items-shorthand-005.html, css-align-3/default-alignment/place-items-shorthand-006.html, css-align-3/resources/alignment-parsing-utils.js, css-align-3/self-alignment/place-self-shorthand-001.html, css-align-3/self-alignment/place-self-shorthand-002.html, css-align-3/self-alignment/place-self-shorthand-003.html, css-align-3/self-alignment/place-self-shorthand-004.html, css-align-3/self-alignment/place-self-shorthand-005.html, css-align-3/self-alignment/place-self-shorthand-006.html
Performed several refactoring on the place¡-content, place-items and place-self alignment shorthands.
Verifying the longhand properties .style values instead of the resolved ones, since the longhand resolved values will be handled by the specific property tests.
Added an additional test to verify the shorthands specified and resolved values serialization.
Plaase, @mrego take a look.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1233)
=> [css-align] Refactoring of the place-xxx shorthand related tests

css-align-3/content-distribution/place-content-shorthand-001.html, css-align-3/content-distribution/place-content-shorthand-002.html, css-align-3/content-distribution/place-content-shorthand-004.html, css-align-3/content-distribution/place-content-shorthand-006.html, css-align-3/default-alignment/place-items-shorthand-001.html, css-align-3/default-alignment/place-items-shorthand-002.html, css-align-3/default-alignment/place-items-shorthand-004.html, css-align-3/default-alignment/place-items-shorthand-006.html, css-align-3/self-alignment/place-self-shorthand-001.html, css-align-3/self-alignment/place-self-shorthand-002.html, css-align-3/self-alignment/place-self-shorthand-004.html, css-align-3/self-alignment/place-self-shorthand-006.html
Using relative paths for utility JS scripts ease the process of importing the tests to the testing infrastructure of different web engines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1234)
=> [css-align] Using relative paths for the utility JS scripts.

css-grid-1/grid-items/grid-minimum-size-grid-items-019.html, css-grid-1/grid-items/grid-minimum-size-grid-items-020.html
As suggested by @svillar I'm adding cases for percentage to verify that they're considered fixed sizes.
Please @svillar or @javifernandez take a look, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1238)
=> [css-grid] Add percentage cases to implied minimum size tests

css-align-3/resources/alignment-parsing-utils.js
The specified value of the place-xxx shorthands will be the common value if both longhand's value are the same. 
The resolved value of "first baseline" will be just "baseline", while we will keep "last baseline" as specified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1240)
=> [css-align] Adjust test expectations to the new baseline-position syntax

build-css-testsuites.sh
This commonly happens when you're already inside a virtualenv, but can
also happen when there are multiple Python interpreters installed (e.g.,
2 and 3) and virtualenv is installed in a different one to the one we
decide to use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1242)
=> Fix the case when virtualenv exists in PATH but not as a module

selectors-4/focus-within-001-ref.html, selectors-4/focus-within-001.html, selectors-4/focus-within-002.html, selectors-4/focus-within-003.html, selectors-4/focus-within-004.html, selectors-4/focus-within-005.html, selectors-4/focus-within-006.html, selectors-4/focus-within-shadow-001-ref.html
I guess the goal of these tests was not to use an invalid markup.
This patch just removes some opening `<body>` tags at the end of the HTML files (just before `</html>`). And fixes a missing `<div>` close tag.
Please @frivoal could you take a look? Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1251)
=> [selectors-4] Fix markup on several :focus-within tests

css-cascade-4/reference/ref-filled-green-100px-square.xht, css-cascade-4/revert-val-001.html
Currently implemented in Safari: http://caniuse.com/#feat=css-revert-value
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1067)
=> [css-cascade] Add simple test for 'revert' keyword value

css-shapes-1/shape-outside/values/support/parsing-utils.js
getPropertyValue returns en empty string in both IE. In chrome there is a proposed changed to update getPropertyValue with an empty string instead of returning null.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/815)
=> Support for getPropertyValue to return empty string

css-flexbox-1/flex-grow-007.html, css-flexbox-1/flex-shrink-008.html
This was accidentally tested prior to #1104 (but incorrectly).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1106)
=> Add test for flex-grow being less than one
