w3c/csswg-test

- css-grid-1/grid-model/grid-float-001.xht
- css-grid-1/grid-model/grid-inline-float-001.xht
> [css-grid] float and clear have no effect on grid items

- css-text-3/text-align-006.html
- css-text-3/text-align-007.html
- css-text-3/text-align-008.html
- Update the reference link for text-align tests
- Update text-align-008.html to use text-align-007-ref.html for reference
> Update reference link for text-align

- css-flexbox-1/align-content-004.htm
- css-flexbox-1/align-items-004.htm
These 2 tests can share a same reftest with other tests.
> Add reference file to align-{content, items}-004

- css-color-3/t422-rgba-clip-outside-device-gamut-b-ref.html
- css-color-3/t422-rgba-clip-outside-device-gamut-b.xht
- css-color-3/t422-rgba-onscreen-b-ref.html
- css-color-3/t422-rgba-onscreen-b.xht
- css-color-3/t424-hsl-clip-outside-gamut-b-ref.html
- css-color-3/t424-hsl-clip-outside-gamut-b.xht
- css-color-3/t424-hsl-values-b-ref.html
- css-color-3/t424-hsl-values-b.xht
- css-color-3/t425-hsla-clip-outside-device-gamut-b-ref.html
- css-color-3/t425-hsla-clip-outside-device-gamut-b.xht
- css-color-3/t425-hsla-values-b-ref.html
- css-color-3/t425-hsla-values-b.xht
Change manual tests in css-color-3 to reftest
> Add reference file for css color tests

- css-writing-modes-3/test-plan/req-tcu-font.html
> Writing Modes test plan: update font reqs document to include glyph mappings

- css-color-3/t422-rgba-onscreen-multiple-boxes-c-ref.html
- css-color-3/t422-rgba-onscreen-multiple-boxes-c.xht
- css-color-3/t425-hsla-onscreen-multiple-boxes-c.xht
Change manual tests in css-color-3 to reftest
> Add reftest to {t422-rgba,t425-hsla}-onscreen-multiple-boxes-c.xht

- css-counter-styles-3/i18n/css3-counter-styles-016.html
- css-counter-styles-3/i18n/css3-counter-styles-021.html
- css-counter-styles-3/i18n/css3-counter-styles-030.html
- css-counter-styles-3/i18n/css3-counter-styles-031.html
- css-counter-styles-3/i18n/css3-counter-styles-033.html
- css-counter-styles-3/i18n/css3-counter-styles-034.html
- css-counter-styles-3/i18n/css3-counter-styles-036.html
- css-counter-styles-3/i18n/css3-counter-styles-037.html
- css-counter-styles-3/i18n/css3-counter-styles-039.html
- css-counter-styles-3/i18n/css3-counter-styles-040.html
- css-counter-styles-3/i18n/css3-counter-styles-050.html
- css-counter-styles-3/i18n/css3-counter-styles-052.html
- css-counter-styles-3/i18n/css3-counter-styles-053.html
- css-counter-styles-3/i18n/css3-counter-styles-055.html
- css-counter-styles-3/i18n/css3-counter-styles-056.html
- css-counter-styles-3/i18n/css3-counter-styles-057.html
- css-counter-styles-3/i18n/css3-counter-styles-058.html
- css-counter-styles-3/i18n/css3-counter-styles-060.html
- css-counter-styles-3/i18n/css3-counter-styles-061.html
- css-counter-styles-3/i18n/css3-counter-styles-062.html
- css-counter-styles-3/i18n/css3-counter-styles-063.html
- css-counter-styles-3/i18n/css3-counter-styles-065.html
- css-counter-styles-3/i18n/css3-counter-styles-066.html
- css-counter-styles-3/i18n/css3-counter-styles-069.html
- css-counter-styles-3/i18n/css3-counter-styles-074.html
- css-counter-styles-3/i18n/css3-counter-styles-079.html
- css-counter-styles-3/i18n/css3-counter-styles-084.html
- css-counter-styles-3/i18n/css3-counter-styles-089.html
Updated hebrew, cjk-decimal, hiragana, hiragana-iroha, katakana, katakana-iroha, upper-roman and lower-roman tests to match changes in the Counter Styles specification prior to CR release.
> Counter-style corrections, pre CR changes

- css-grid-1/grid-model/grid-floats-no-intrude-001.xht
- css-grid-1/grid-model/grid-inline-floats-no-intrude-001.xht
> [css-grid] floats do not intrude into grid containers

- css-grid-1/grid-model/grid-inline-margins-no-collapse-001.xht
- css-grid-1/grid-model/grid-margins-no-collapse-001.xht
- css-grid-1/reference/grid-text-green-margin-no-collapse-ref.xht
> [css-grid] grid's margins do not collapse

- css-grid-1/grid-model/grid-inline-multicol-001.xht
- css-grid-1/grid-model/grid-multicol-001.xht
> [css-grid] column-* properties have no effect on a grid container

- css-grid-1/grid-model/grid-computed-value-display-floated-items-001.xht
> [css-grid] 'float' affects to the computed value of 'display' on grid items

- css-grid-1/grid-items/grid-inline-items-001.xht
- css-grid-1/grid-items/grid-inline-items-002.xht
- css-grid-1/grid-items/grid-inline-items-003.xht
- css-grid-1/grid-items/grid-items-001.xht
- css-grid-1/grid-items/grid-items-002.xht
- css-grid-1/grid-items/grid-items-003.xht
> [css-grid] Grid items

- css-grid-1/grid-items/grid-inline-order-property-painting-001.xht
- css-grid-1/grid-items/grid-inline-order-property-painting-002.xht
- css-grid-1/grid-items/grid-inline-order-property-painting-003.xht
- css-grid-1/grid-items/grid-inline-order-property-painting-004.xht
- css-grid-1/grid-items/grid-inline-order-property-painting-005.xht
- css-grid-1/grid-items/grid-order-property-painting-001.xht
- css-grid-1/grid-items/grid-order-property-painting-002.xht
- css-grid-1/grid-items/grid-order-property-painting-003.xht
- css-grid-1/grid-items/grid-order-property-painting-004.xht
- css-grid-1/grid-items/grid-order-property-painting-005.xht
- css-grid-1/reference/grid-text-green-margin-no-collapse-ref.xht
> [css-grid] order property affects grid items painting order

- css-grid-1/grid-items/grid-inline-order-property-auto-placement-001.xht
- css-grid-1/grid-items/grid-inline-order-property-auto-placement-002.xht
- css-grid-1/grid-items/grid-inline-order-property-auto-placement-003.xht
- css-grid-1/grid-items/grid-inline-order-property-auto-placement-004.xht
- css-grid-1/grid-items/grid-inline-order-property-auto-placement-005.xht
- css-grid-1/grid-items/grid-order-property-auto-placement-001.xht
- css-grid-1/grid-items/grid-order-property-auto-placement-002.xht
- css-grid-1/grid-items/grid-order-property-auto-placement-003.xht
- css-grid-1/grid-items/grid-order-property-auto-placement-004.xht
- css-grid-1/grid-items/grid-order-property-auto-placement-005.xht
- css-grid-1/reference/grid-2x2-blue-yellow-lime-magenta.xht
> [css-grid] order property affects grid items auto-placement position

- css-grid-1/grid-items/grid-inline-z-axis-ordering-001.xht
- css-grid-1/grid-items/grid-inline-z-axis-ordering-002.xht
- css-grid-1/grid-items/grid-inline-z-axis-ordering-003.xht
- css-grid-1/grid-items/grid-inline-z-axis-ordering-004.xht
- css-grid-1/grid-items/grid-inline-z-axis-ordering-005.xht
- css-grid-1/grid-items/grid-inline-z-axis-ordering-overlapped-items-001.xht
- css-grid-1/grid-items/grid-inline-z-axis-ordering-overlapped-items-002.xht
- css-grid-1/grid-items/grid-inline-z-axis-ordering-overlapped-items-003.xht
- css-grid-1/grid-items/grid-inline-z-axis-ordering-overlapped-items-004.xht
- css-grid-1/grid-items/grid-inline-z-axis-ordering-overlapped-items-005.xht
- css-grid-1/grid-items/grid-inline-z-axis-ordering-overlapped-items-006.xht
- css-grid-1/grid-items/grid-z-axis-ordering-001.xht
- css-grid-1/grid-items/grid-z-axis-ordering-002.xht
- css-grid-1/grid-items/grid-z-axis-ordering-003.xht
- css-grid-1/grid-items/grid-z-axis-ordering-004.xht
- css-grid-1/grid-items/grid-z-axis-ordering-005.xht
- css-grid-1/grid-items/grid-z-axis-ordering-overlapped-items-001.xht
- css-grid-1/grid-items/grid-z-axis-ordering-overlapped-items-002.xht
- css-grid-1/grid-items/grid-z-axis-ordering-overlapped-items-003.xht
- css-grid-1/grid-items/grid-z-axis-ordering-overlapped-items-004.xht
- css-grid-1/grid-items/grid-z-axis-ordering-overlapped-items-005.xht
- css-grid-1/grid-items/grid-z-axis-ordering-overlapped-items-006.xht
- css-grid-1/reference/grid-filled-blue-yellow-green-overlapped-100px-squares.xht
> [css-grid] z-index property

- css-grid-1/grid-items/grid-inline-items-inline-blocks-001.xht
- css-grid-1/grid-items/grid-items-inline-blocks-001.xht
> [css-grid] Paint items as inline blocks

- css-grid-1/grid-definition/grid-inline-support-grid-template-columns-rows-001.xht
- css-grid-1/grid-definition/grid-support-grid-template-columns-rows-001.xht
> [css-grid] grid-template-rows and grid-template-columns properties

- css-grid-1/grid-definition/grid-inline-support-named-grid-lines-001.xht
- css-grid-1/grid-definition/grid-support-named-grid-lines-001.xht
> [css-grid] Named grid lines

- css-grid-1/grid-definition/grid-inline-support-repeat-001.xht
- css-grid-1/grid-definition/grid-support-repeat-001.xht
> [css-grid] repeat() notation

- css-grid-1/grid-definition/grid-inline-template-columns-rows-resolved-values-001.xht
- css-grid-1/grid-definition/grid-template-columns-rows-resolved-values-001.xht
This covers first case of #648.
> [css-grid] Resolved values of grid-template-rows and grid-template-columns for implicit tracks

- css-grid-1/grid-definition/grid-inline-support-flexible-lengths-001.xht
- css-grid-1/grid-definition/grid-support-flexible-lengths-001.xht
> [css-grid] Flexible lengths: fr unit

- css-color-3/t31-color-currentColor-b-ref.html
- css-color-3/t31-color-currentColor-b.xht
- css-color-3/t421-rgb-func-int-a.xht
- css-color-3/t421-rgb-func-no-mixed-f.xht
- css-color-3/t421-rgb-func-pct-a.xht
- css-color-3/t421-rgb-func-whitespace-b.xht
- css-color-3/t421-rgb-hex-parsing-f.xht
- css-color-3/t421-rgb-hex3-a.xht
- css-color-3/t421-rgb-hex6-a.xht
- css-color-3/t422-rgba-a1.0-a-ref.html
- css-color-3/t422-rgba-a1.0-a.xht
- css-color-3/t422-rgba-func-pct-a.xht
Add 2 new ref files, and the other tests share the old ref file.
> Update manual tests to ref

- css-grid-1/grid-definition/grid-inline-support-grid-template-areas-001.xht
- css-grid-1/grid-definition/grid-support-grid-template-areas-001.xht
- css-grid-1/grid-definition/support/testing-utils.js
> [css-grid] grid-template-areas property

- css-text-3/white-space/seg-break-transformation-000.html
- css-text-3/white-space/seg-break-transformation-001.html
- css-text-3/white-space/seg-break-transformation-002.html
- css-text-3/white-space/seg-break-transformation-003.html
- css-text-3/white-space/seg-break-transformation-004.html
- css-text-3/white-space/seg-break-transformation-005.html
- css-text-3/white-space/seg-break-transformation-006.html
- css-text-3/white-space/seg-break-transformation-007.html
- css-text-3/white-space/seg-break-transformation-008.html
- css-text-3/white-space/seg-break-transformation-009.html
- css-text-3/white-space/seg-break-transformation-010.html
- css-text-3/white-space/seg-break-transformation-011.html
- css-text-3/white-space/seg-break-transformation-012.html
- css-text-3/white-space/seg-break-transformation-014.html
- css-text-3/white-space/seg-break-transformation-015.html
- css-text-3/white-space/seg-break-transformation-016.html
- css-text-3/white-space/seg-break-transformation-017.html
- css-text-3/white-space/white-space-collapse-000.html
- css-text-3/white-space/white-space-collapse-001.html
- css-text-3/white-space/white-space-collapse-002.html
these are all testharness.js tests; the link to the javascript is relative so that these tests work in the i18n test suite repository as well as here. I'm hoping they will work fine.
> tests for css-text-3 white-space processing rules

- css-values-3/ch-unit-001.html
- css-values-3/reference/ch-unit-001-ref.html
Basic test for the ch unit, interesting in particular because IE fails it despite implementing the unit.
> [css-values-3] Add test case for the ch unit

- css-writing-modes-3/text-combine-upright/reference/value-single-character-ref.html
- css-writing-modes-3/text-combine-upright/value-all-001.html
- css-writing-modes-3/text-combine-upright/value-digits2-001.html
TCY is supposed to rotate even the resulting composition is made of a single character.
addressing the last bits of #568
> Writing Modes: add tests for TCY of single character

- selectors-4/hover-001-manual.html
Refs https://connect.microsoft.com/IE/feedback/details/926665 & https://github.com/twbs/bootstrap/issues/14211
> Add test for scrolling away from an element that was :hover-ed over

- css21/tables/border-collapse-005-ref.html
- css21/tables/border-collapse-005.html
Refs http://bugzil.la/1023761 & https://github.com/twbs/bootstrap/issues/13453
> Add test of sanity of collapsing borders when there's an empty <tbody>

- README.md
Make it point to this repo instead of a different repo.
> README: Update link to CONTRIBUTING.md

- css21/values/numbers-units-015.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/849)
> Fix typos in numbers-units-015.xht.

- css21/syntax/at-charset-001-ref.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/850)
> Add missing file.

- vendor-imports/mozilla/mozilla-central-reftests/variables/support/external-variable-font-face.css
- vendor-imports/mozilla/mozilla-central-reftests/variables/variable-external-font-face-01-ref.html
- vendor-imports/mozilla/mozilla-central-reftests/variables/variable-font-face-01-ref.html
- vendor-imports/mozilla/mozilla-central-reftests/variables/variable-font-face-01.html
- vendor-imports/mozilla/mozilla-central-reftests/variables/variable-font-face-02-ref.html
- vendor-imports/mozilla/mozilla-central-reftests/variables/variable-font-face-02.html
https://hg.mozilla.org/integration/mozilla-inbound/rev/4f4bdab7f61d
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/853)
> Update Mozilla tests

- css21/visuren/left-offset-position-fixed-001-ref.xht
- css21/visuren/left-offset-position-fixed-001.xht
- css21/visuren/right-offset-position-fixed-001-ref.xht
- css21/visuren/right-offset-position-fixed-001.xht
Refs http://wkbug.com/147284, https://github.com/twbs/bootstrap/issues/16814
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/813)
> [CSS21][CSS22] Add regression test for position:fixed edge case

- css21/fonts/font-003-ref.html
- css21/fonts/font-003.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/869)
> Add reference file for font case

- css21/cascade-import/cascade-import-dynamic-001.xht
- css21/cascade-import/cascade-import-dynamic-002.xht
- css21/cascade-import/cascade-import-dynamic-003.xht
- css21/cascade-import/cascade-import-dynamic-004.xht
- css21/cascade-import/cascade-import-dynamic-005.xht
- css21/cascade-import/cascade-import-dynamic-006.xht
- css21/cascade-import/cascade-import-dynamic-control.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/872)
> Fix a typo in the extension of some reference URLs.

- css-text-decor-3/text-emphasis-style-001.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/874)
> css-text-decor-3/text-emphasis-style-001: Fix encoding and typos

- css21/sec5/descendant-selector-000-ref.xht
- css21/sec5/descendant-selector-000.xht
- css21/sec5/descendant-selector-001.xht
- css21/sec5/grouping-000-notref.xht
- css21/sec5/grouping-000-ref.xht
- css21/sec5/grouping-000.xht
- css21/sec5/grouping-001.xht
- css21/selectors/descendent-selector-002-ref.xht
- css21/selectors/descendent-selector-002.xht
- css21/selectors/descendent-selector-003.xht
- css21/selectors/descendent-selector-004-ref.xht
- css21/selectors/descendent-selector-004.xht
- css21/selectors/descendent-selector-006.xht
- css21/selectors/grouping-002-notref.xht
- css21/selectors/grouping-002-ref.xht
- css21/selectors/grouping-002.xht
- css21/selectors/type-selector-001-ref.xht
- css21/selectors/type-selector-001.xht
- css21/selectors/universal-selector-001-notref.xht
- css21/selectors/universal-selector-001-ref.xht
- css21/selectors/universal-selector-001.xht
- css21/selectors/universal-selector-002-notref.xht
- css21/selectors/universal-selector-002-ref.xht
- css21/selectors/universal-selector-002.xht
- css21/selectors/universal-selector-005-ref.xht
- css21/selectors/universal-selector-005.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/886)
> Add references to some CSS2.1 selector tests.

- css21/selectors/descendent-selector-007.xht
- css21/selectors/descendent-selector-008.xht
- css21/selectors/descendent-selector-009.xht
- css21/selectors/descendent-selector-010.xht
- css21/selectors/descendent-selector-011.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/892)
> Add references for descendent-selector-007.xht through descendent-selector-011.xht.

- css-color-3/t421-rgb-hex-parsing-f.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/891)
> Remove obsoleted test from t421-rgb-hex-parsing-f.xht.

- css-flexbox-1/order/order-with-column-reverse-ref.html
- css-flexbox-1/order/order-with-column-reverse.html
The reference file looks different from the test file due to margin collapsing.
Just use margin: 0; in both files -- the test does not depend on margins.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/884)
> [css-flexbox] Fix order-with-column-reverse.html

- css-flexbox-1/align-items-004.htm
leading Chrome to fail the test unnecessarily.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/895)
> [css-flexbox] Adjust gradient to avoid anti-aliasing at the wrong place,

- css-flexbox-1/flexbox_direction-row-reverse-ref.html
Instead of depending on any specific font size, just size each item
at 10/3em.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/905)
> [css-flexbox-1] Fix flexbox_direction-row-reverse-ref.html

- css21/sec5/adjacent-000-ref.xht
- css21/sec5/adjacent-000.xht
- css21/sec5/adjacent-001.xht
- css21/sec5/adjacent-002.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/897)
> Add a reference for adjacent-000.xht, adjacent-001.xht, and adjacent-002.xht.

- css21/selectors/dynamic-sibling-combinator-001-ref.xht
- css21/selectors/dynamic-sibling-combinator-001.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/912)
> Add a reference for dynamic-sibling-combinator-001.xht.

- css21/selectors/sibling-selector-001-ref.xht
- css21/selectors/sibling-selector-001.xht
- css21/selectors/sibling-selector-003-ref.xht
- css21/selectors/sibling-selector-003.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/913)
>  Add references for sibling-selector-001.xht and sibling-selector-003.xht. 

- css21/sec5/attribute-000.xht
- css21/sec5/attribute-001.xht
- css21/sec5/attribute-002.xht
- css21/sec5/attribute-003.xht
- css21/sec5/attribute-004.xht
- css21/sec5/attribute-005.xht
- css21/sec5/attribute-006.xht
- css21/sec5/attribute-007.xht
- css21/sec5/attribute-ref.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/917)
> Add a reference for attribute-000.xht through attribute-007.xht.

- .travis.yml
- tools/travis/build.py
Docs: http://docs.travis-ci.com/user/caching/#Arbitrary-directories
Closes #861.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/908)
> Travis CI build: Cache tools repos

- css21/selectors/attribute-value-selector-001-ref.xht
- css21/selectors/attribute-value-selector-001.xht
- css21/selectors/attribute-value-selector-002.xht
- css21/selectors/attribute-value-selector-003.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/920)
> Add a reference for attribute-value-selector-001.xht through attribute-value-selector-003.xht.

- css21/selectors/lang-selector-001-ref.xht
- css21/selectors/lang-selector-001.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/924)
> Add a reference for lang-selector-001.xht.

- css21/selectors/before-after-selector-001-ref.xht
- css21/selectors/before-after-selector-001.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/927)
> Add a reference for before-after-selector-001.xht.

- css21/selectors/before-first-letter-selector-001-ref.xht
- css21/selectors/before-first-letter-selector-001.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/929)
> Add a reference for before-first-letter-selector-001.xht.

- css-flexbox-1/flex-minimum-height-flex-items-001.xht
- css-flexbox-1/flex-minimum-height-flex-items-002.xht
- css-flexbox-1/flex-minimum-height-flex-items-003.xht
- css-flexbox-1/flex-minimum-height-flex-items-004.xht
- css-flexbox-1/flex-minimum-height-flex-items-005.xht
- css-flexbox-1/flex-minimum-height-flex-items-006.xht
- css-flexbox-1/flex-minimum-height-flex-items-007.xht
- css-flexbox-1/flex-minimum-height-flex-items-008.xht
- css-flexbox-1/flex-minimum-width-flex-items-001.xht
- css-flexbox-1/flex-minimum-width-flex-items-002.xht
- css-flexbox-1/flex-minimum-width-flex-items-003.xht
- css-flexbox-1/flex-minimum-width-flex-items-004.xht
- css-flexbox-1/flex-minimum-width-flex-items-005.xht
- css-flexbox-1/flex-minimum-width-flex-items-006.xht
- css-flexbox-1/flex-minimum-width-flex-items-007.xht
- css-flexbox-1/flex-minimum-width-flex-items-008.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/939)
> [css-flexbox] spelling fix: minimun -> minimum

- cssom-view-1/cssom-getBoundingClientRect-001.html
* Reformat CSS so it's readable
* Improve phrasing of assertion descriptions
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/941)
> [merge] [cssom-view-1] Cleanup cssom-getBoundingClientRect-001.html

- cssom-view-1/htmlelement-offset-width-001.html
Test based on bug servo/servo#8240.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/928)
> Add a test for `offsetWidth`, detached elements.

- css21/backgrounds/background-root-101.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/945)
> Use reftest-wait to ensure background-root-101.xht does not finish early.

- css-backgrounds-3/background-clip-content-box.html
- css-backgrounds-3/border-image-repeat_repeatnegx_none_50px.html
- css-backgrounds-3/reference/reference.html
- work-in-progress/ttwf_bj/tang,shaofeng/border-image-repeat_repeatnegx_none_50px.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/948)
> Fix typos of "background"

- css-grid-1/grid-items/grid-minimum-size-grid-items-001.xht
- css-grid-1/grid-items/grid-minimum-size-grid-items-002.xht
- css-grid-1/grid-items/grid-minimum-size-grid-items-003.xht
- css-grid-1/grid-items/grid-minimum-size-grid-items-004.xht
- css-grid-1/grid-items/grid-minimum-size-grid-items-005.xht
- css-grid-1/grid-items/grid-minimum-size-grid-items-006.xht
- css-grid-1/grid-items/grid-minimum-size-grid-items-007.xht
- css-grid-1/grid-items/grid-minimum-size-grid-items-008.xht
- css-grid-1/grid-items/grid-minimum-size-grid-items-009.xht
s/minimun/minimum
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/958)
> [css-grid] Fixed typo in minimum size tests

- cssom-1/interfaces.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/963)
> Add an idlharness test for CSSOM.

- cssom-1/escape.html
This covers <https://github.com/w3c/csswg-drafts/commit/c2028630eaabcd07573ba4df11b8e8ecf653eeaf>.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/965)
> Update CSS.escape test for null change.

- work-in-progress/boland/css/534-5.htm
- work-in-progress/boland/css2/7-08.htm
- work-in-progress/boland/css2/73-1.htm
- work-in-progress/boland/css2/73-2.htm
- work-in-progress/boland/css2/73-3.htm
- work-in-progress/boland/css2/73-4.htm
- work-in-progress/boland/css2/73-5.htm
- work-in-progress/boland/css3/spec/xbc1.xml
- work-in-progress/boland/css3/spec/xbc2.xml
- work-in-progress/boland/css3/spec/xbc3.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/949)
> Fix typos of "background" in Boland WIP

- css-shapes-1/spec-examples/shape-outside-002.html
- css-shapes-1/spec-examples/shape-outside-003.html
- css-shapes-1/spec-examples/shape-outside-004.html
- css-shapes-1/spec-examples/shape-outside-005.html
- css-transforms-1/perspective-translateZ-negative.html
- css-transforms-1/perspective-translateZ-positive.html
- css-transforms-1/transform-origin-01.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/960)
> Avoid non-ASCII characters in files without charset declarations.

- css21/lists/counter-increment-005.xht
- css21/lists/counter-increment-006.xht
- css21/lists/counter-increment-007.xht
- css21/lists/counter-increment-018.xht
- css21/lists/counter-increment-019.xht
- css21/lists/counter-increment-020.xht
- css21/lists/counter-increment-031.xht
- css21/lists/counter-increment-032.xht
- css21/lists/counter-increment-033.xht
- css21/lists/counter-increment-044.xht
- css21/lists/counter-increment-045.xht
- css21/lists/counter-increment-046.xht
- css21/lists/counter-reset-005.xht
- css21/lists/counter-reset-006.xht
- css21/lists/counter-reset-007.xht
- css21/lists/counter-reset-014.xht
- css21/lists/counter-reset-018.xht
- css21/lists/counter-reset-019.xht
- css21/lists/counter-reset-020.xht
- css21/lists/counter-reset-027.xht
- css21/lists/counter-reset-031.xht
- css21/lists/counter-reset-032.xht
- css21/lists/counter-reset-033.xht
- css21/lists/counter-reset-040.xht
- css21/lists/counter-reset-044.xht
- css21/lists/counter-reset-045.xht
- css21/lists/counter-reset-046.xht
- css21/lists/counter-reset-055.xht
- css21/reference/pass-if-number-0-30px.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/973)
> Add pass-if-number-0-30px from presto-testo & add matches.

- css-box-3/font-variant-applies-to-004.xht
- css21/fonts/font-variant-applies-to-001.xht
- css21/fonts/font-variant-applies-to-002.xht
- css21/fonts/font-variant-applies-to-005.xht
- css21/fonts/font-variant-applies-to-006.xht
- css21/fonts/font-variant-applies-to-007.xht
- css21/fonts/font-variant-applies-to-008.xht
- css21/fonts/font-variant-applies-to-009.xht
- css21/fonts/font-variant-applies-to-010.xht
- css21/fonts/font-variant-applies-to-011.xht
- css21/fonts/font-variant-applies-to-014.xht
- css21/fonts/font-variant-applies-to-015.xht
- css21/fonts/font-variant-applies-to-017.xht
- css21/reference/pass_if_filler_text_match.xht
- css21/reference/pass_if_filler_text_match_smallcaps.xht
This also adds a check that it's actually smallcaps.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/974)
> Add pass_if_filler_text_match_smallcaps.xht & add matches

- css-box-3/list-style-applies-to-011.xht
- css-box-3/list-style-type-applies-to-011.xht
- css21/lists/list-style-applies-to-001.xht
- css21/lists/list-style-applies-to-002.xht
- css21/lists/list-style-applies-to-003.xht
- css21/lists/list-style-applies-to-004.xht
- css21/lists/list-style-applies-to-007.xht
- css21/lists/list-style-applies-to-008.xht
- css21/lists/list-style-applies-to-009.xht
- css21/lists/list-style-applies-to-010.xht
- css21/lists/list-style-applies-to-012.xht
- css21/lists/list-style-applies-to-013.xht
- css21/lists/list-style-applies-to-014.xht
- css21/lists/list-style-applies-to-015.xht
- css21/lists/list-style-type-applies-to-001.xht
- css21/lists/list-style-type-applies-to-002.xht
- css21/lists/list-style-type-applies-to-003.xht
- css21/lists/list-style-type-applies-to-004.xht
- css21/lists/list-style-type-applies-to-007.xht
- css21/lists/list-style-type-applies-to-008.xht
- css21/lists/list-style-type-applies-to-009.xht
- css21/lists/list-style-type-applies-to-010.xht
- css21/lists/list-style-type-applies-to-012.xht
- css21/lists/list-style-type-applies-to-013.xht
- css21/lists/list-style-type-applies-to-014.xht
- css21/lists/list-style-type-applies-to-015.xht
- css21/reference/single_square_list_marker.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/975)
> Add single_square_list_marker from presto-test & add matches

- css-box-3/font-weight-applies-to-004.xht
- css21/fonts/font-weight-applies-to-005.xht
- css21/fonts/font-weight-applies-to-006.xht
- css21/fonts/font-weight-applies-to-007.xht
- css21/fonts/font-weight-applies-to-008.xht
- css21/fonts/font-weight-applies-to-009.xht
- css21/fonts/font-weight-applies-to-010.xht
- css21/fonts/font-weight-applies-to-011.xht
- css21/fonts/font-weight-applies-to-014.xht
- css21/fonts/font-weight-applies-to-015.xht
- reference/pass_if_filler_text_match_bold.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/977)
> Add pass_if_filler_text_match_bold.xht & add matches.

- css-box-3/font-style-applies-to-004.xht
- css21/fonts/font-style-applies-to-005.xht
- css21/fonts/font-style-applies-to-006.xht
- css21/fonts/font-style-applies-to-007.xht
- css21/fonts/font-style-applies-to-008.xht
- css21/fonts/font-style-applies-to-009.xht
- css21/fonts/font-style-applies-to-010.xht
- css21/fonts/font-style-applies-to-011.xht
- css21/fonts/font-style-applies-to-014.xht
- reference/pass_if_filler_text_slanted.xht
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/978)
> Add pass_if_filler_text_slanted and add matches

- css-writing-modes-3/table-progression-slr-001-ref.html
- css-writing-modes-3/table-progression-slr-001.html
- css-writing-modes-3/table-progression-srl-001.html
- css-writing-modes-3/table-progression-srl-002.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/983)
> Add charset declarations to some table-progression tests.

- css-grid-1/implicit-grids/grid-support-grid-auto-columns-rows-001.html
- css-grid-1/reference/grid-support-grid-auto-columns-rows-001-ref.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/976)
>  [css-grid] Add grid-layout-auto-columns/grid-layout-auto-rows test

- css-transforms-1/transform-2d-getComputedStyle-001.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/986)
> Correct an author name.

- selectors-3/selectors-empty-001-ref.xml
- selectors-3/selectors-empty-001.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/996)
> Submit selectors-empty-001.xml.

- css-text-3/text-justify/text-justify-001.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1015)
> Fix the link to the text-justify-ref-001.html reference.

- css21/zindex/stack-floats-001.xht
- css21/zindex/stack-floats-002.xht
- css21/zindex/stack-floats-003.xht
- css21/zindex/stack-floats-004.xht
- cssom-view-1/elementFromPosition.html
- work-in-progress/ttwf_bj/Chris/elementFromPosition.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1024)
> Fix "botom" and "nagetive" typos

- css21/zindex/z-index-dynamic-001.xht
- mediaqueries-3/aspect-ratio-001.html
- mediaqueries-3/aspect-ratio-002.html
- mediaqueries-3/aspect-ratio-003.html
- mediaqueries-3/aspect-ratio-004.html
- mediaqueries-3/device-aspect-ratio-002.html
- mediaqueries-3/device-aspect-ratio-003.html
- mediaqueries-3/device-aspect-ratio-004.html
Add one ref, and fix a whole load links.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1034)
> Make sure everything links to ref-filled-green-100px-square.xht

- css-box-3/text-transform-applies-to-004.xht
- css21/text/text-transform-applies-to-001.xht
- css21/text/text-transform-applies-to-002.xht
- css21/text/text-transform-applies-to-005.xht
- css21/text/text-transform-applies-to-006.xht
- css21/text/text-transform-applies-to-007.xht
- css21/text/text-transform-applies-to-008.xht
- css21/text/text-transform-applies-to-009.xht
- css21/text/text-transform-applies-to-010.xht
- css21/text/text-transform-applies-to-011.xht
- css21/text/text-transform-applies-to-012.xht
- css21/text/text-transform-applies-to-013.xht
- css21/text/text-transform-applies-to-014.xht
- css21/text/text-transform-applies-to-015.xht
- reference/pass_if_letter_uppercase.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1035)
> Add pass if letter uppercase as a ref

- css-text-3/text-transform/text-transform-capitalize-030.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1038)
> Fix reference link.

- mediaqueries-3/device-aspect-ratio-001.html
- mediaqueries-3/device-aspect-ratio-005.html
- mediaqueries-3/device-aspect-ratio-006.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1046)
> Fix more instances of <link name="match"> (instead of @rel)

- css-box-3/text-decoration-applies-to-004.xht
- css21/text/text-decoration-applies-to-001.xht
- css21/text/text-decoration-applies-to-002.xht
- css21/text/text-decoration-applies-to-005.xht
- css21/text/text-decoration-applies-to-006.xht
- css21/text/text-decoration-applies-to-007.xht
- css21/text/text-decoration-applies-to-008.xht
- css21/text/text-decoration-applies-to-009.xht
- css21/text/text-decoration-applies-to-010.xht
- css21/text/text-decoration-applies-to-011.xht
- css21/text/text-decoration-applies-to-014.xht
- css21/text/text-decoration-applies-to-015.xht
- reference/pass_if_filler_text_underlined-notref.html
- reference/pass_if_filler_text_underlined.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1051)
> Add pass_if_filler_text_underlined reference and matches.

- css-box-3/letter-spacing-applies-to-004.xht
- css21/text/letter-spacing-applies-to-001.xht
- css21/text/letter-spacing-applies-to-002.xht
- css21/text/letter-spacing-applies-to-006.xht
- css21/text/letter-spacing-applies-to-008.xht
- css21/text/letter-spacing-applies-to-009.xht
- css21/text/letter-spacing-applies-to-010.xht
- css21/text/letter-spacing-applies-to-011.xht
- css21/text/letter-spacing-applies-to-014.xht
- css21/text/letter-spacing-applies-to-015.xht
- reference/black_box_ends_when_blue_box_ends_6_boxes_ahem.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1047)
> Add black_box_ends_when_blue_box_ends_6_boxes_ahem and matches

- css21/generated-content/content-107.xht
- css21/generated-content/content-108.xht
- css21/generated-content/content-110.xht
- css21/generated-content/content-111.xht
- css21/generated-content/content-112.xht
- css21/generated-content/content-114.xht
- css21/generated-content/content-115.xht
- css21/generated-content/content-116.xht
- css21/generated-content/content-117.xht
- css21/generated-content/content-118.xht
- css21/generated-content/content-119.xht
- css21/generated-content/content-121.xht
- reference/only_pass_parens_semicolon.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1045)
> Add only_pass_parens_semicolon reference and matches.

- cssom-view-1/CaretPosition-001.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1058)
> Cleanup CaretPosition-001.html.

- css-color-3/t31-color-text-a-ref.xht
- css-color-3/t31-color-text-a.xht
- css21/selectors/class-selector-008.xht
- css21/selectors/first-line-pseudo-018.xht
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1053)
> Add refs for "this text should be green"

- css-cascade-3/initial-color-background-001-ref.html
- css-cascade-3/initial-color-background-001.html
https://drafts.csswg.org/css-cascade/#initial
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/856)
> [css-cascade] Add basic test of the "initial" value

- css-cascade-3/unset-val-002.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/858)
> [css-cascade] Add test for display:unset;

- css-cascade-3/reference/ref-filled-green-100px-square.xht
- css-cascade-3/unset-val-001.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/857)
> [css-cascade] Add basic (background-)color test of the "unset" value

- css-cascade-3/all-prop-002.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/860)
> [css-cascade] Test that all:inherit causes display:inherit

- css-cascade-3/all-prop-001-ref.html
- css-cascade-3/all-prop-001.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/859)
> [css-cascade] Test that "all" shorthand excludes "direction"

- geometry-1/DOMMatrix-002.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1061)
> Test DOMMatrixReadOnly methods do not mutate

- css-flexbox-1/flex-aspect-ratio-img-column-001.html
- css-flexbox-1/flex-aspect-ratio-img-column-002.html
- css-flexbox-1/flex-aspect-ratio-img-column-003.html
- css-flexbox-1/flex-aspect-ratio-img-row-001.html
- css-flexbox-1/flex-aspect-ratio-img-row-002.html
- css-flexbox-1/flex-aspect-ratio-img-row-003.html
r? @fantasai
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1028)
> [css-flexbox-1] Add basic tests for aspect ratio handling

- tools/travis/build.py
@jgraham @Ms2ger  plz review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1070)
> Travis build improvements

- css21/backgrounds/background-body-001.xht
- css21/backgrounds/background-body-002.xht
- css21/backgrounds/background-body-003.xht
- css21/backgrounds/background-html-body-001.xht
- css21/generated-content/content-066.xht
- css21/generated-content/content-081.xht
- css21/generated-content/content-090.xht
- css21/generated-content/content-091.xht
- css21/generated-content/content-149.xht
- css21/generated-content/content-153.xht
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1072)
> Remove some unnecessary HTMLonly flags.

- selectors-4/selector-required.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1076)
> [selectors-4] Fix typo: optinal => optional

- cssom-view-1/matchMediaAddListener.html
Clean up `/cssom-view-1/matchMediaAddListener.html`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1081)
> Self-closing script tags don't work in plain HTML.

- geometry-1/DOMMatrix-001.html
- geometry-1/DOMMatrix-002.html
- geometry-1/DOMMatrix-003.html
- geometry-1/support/dommatrix-test-util.js
And renamed DOMMatrix-003.htm to have the same extension as the others.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1082)
> Move common DOMMatrix test functions into support dir

- css21/text/letter-spacing-004-ref.xht
- css21/text/letter-spacing-004.xht
- css21/text/letter-spacing-005.xht
- css21/text/letter-spacing-006.xht
- css21/text/letter-spacing-016.xht
- css21/text/letter-spacing-017.xht
- css21/text/letter-spacing-018.xht
- css21/text/letter-spacing-028.xht
- css21/text/letter-spacing-029.xht
- css21/text/letter-spacing-030.xht
- css21/text/letter-spacing-040.xht
- css21/text/letter-spacing-041.xht
- css21/text/letter-spacing-042.xht
- css21/text/letter-spacing-052.xht
- css21/text/letter-spacing-053.xht
- css21/text/letter-spacing-054.xht
- css21/text/letter-spacing-064.xht
- css21/text/letter-spacing-065.xht
- css21/text/letter-spacing-066.xht
- css21/text/letter-spacing-076.xht
- css21/text/letter-spacing-077.xht
- css21/text/letter-spacing-078.xht
- css21/text/letter-spacing-088.xht
- css21/text/letter-spacing-089.xht
- css21/text/letter-spacing-090.xht
- css21/text/letter-spacing-097.xht
- css21/text/letter-spacing-098.xht
- css21/text/letter-spacing-099.xht
- css21/text/letter-spacing-100.xht
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1086)
> Add a reference for letter-spacing-004 and similar.

- css-ui-3/caret-color-001.html
- css-ui-3/caret-color-002.html
- css-ui-3/caret-color-003.html
- css-ui-3/caret-color-004.html
- css-ui-3/caret-color-005.html
- css-ui-3/caret-color-006.html
- css-ui-3/caret-color-007.html
- css-ui-3/caret-color-008.html
- css-ui-3/caret-color-009.html
The first 3 are updates to previous tests from Chris because the spec changed after he wrote them, and based on reviews here:
http://test.csswg.org/shepherd/testcase/caret-color-001/spec/css-ui-3/
http://test.csswg.org/shepherd/testcase/caret-color-002/spec/css-ui-3/
http://test.csswg.org/shepherd/testcase/caret-color-003/spec/css-ui-3/
The rest are new tests.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/916)
> Test for caret-color

- tools/travis/build.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1095)
> Update submodules on travis.

- css-regions-1/elements/video-001.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1105)
> Remove an unnecessary help link from video-001.html.

- .gitignore
- .gitmodules
- .hgignore
- README.md
- config.default.json
- serve
- serve.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1116)
> Start using wptserve for this. Add everything and docs.

- css-transforms-1/transform_translate.html
- css-transforms-1/transform_translate_invalid.html
- css-transforms-1/transform_translate_max.html
- css-transforms-1/transform_translate_min.html
- css-transforms-1/transform_translate_neg.html
- css-transforms-1/transform_translate_second_omited.html
- css-transforms-1/transform_translate_zero.html
- css-ui-3/caret-color-009.html
- css-values-3/calc-unit-analysis.html
- css-variables-1/test_variable_legal_values.html
- work-in-progress/adobe/css3-regions/css-om-Document.getFlowByName.html
- work-in-progress/aryehgregor/2d-transforms.html
- work-in-progress/aryehgregor/3d-transforms.html
- work-in-progress/aryehgregor/transitions/test_transitions.html
- work-in-progress/aryehgregor/transitions/test_transitions_per_property.html
- work-in-progress/ttwf_bj/neo_and_rayi/extensions_to_the_HTMLElement_interface.html
- work-in-progress/ttwf_tokyo/hiromitsuuuuu/test_font_face_parser.html
- work-in-progress/ttwf_tokyo/t32k/css-fonts-font-face-rule.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1121)
> Use correct paths to testharness.js and testharnessreport.js.

- css-shapes-1/shape-outside/shape-image/gradients/shape-outside-radial-gradient-001.html
- css-shapes-1/shape-outside/shape-image/gradients/shape-outside-radial-gradient-002.html
- css-shapes-1/shape-outside/shape-image/gradients/shape-outside-radial-gradient-003.html
- css-shapes-1/shape-outside/shape-image/gradients/shape-outside-radial-gradient-004.html
- css-transforms-1/2d-rotate-js.html
They are ignored outside it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1123)
> Move testharness.js inclusions into the head element.

- compositing-1/compositing_simple_div.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1124)
> Fix scheme in spec link (hhttp v. http)

- selectors-3/selectors-namespace-001-ref.xml
- selectors-3/selectors-namespace-001.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/998)
> Submit selectors-namespace-001.

- .travis.yml
- css21/visufx/overflow-009.html
- lint.whitelist
Should check Travis runs this PR correctly first, obviously!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1144)
> Split Travis into two jobs to make what failed clearer at a glance

- css-ui-3/caret-color-018.html
Creating a testharness method so this test can be automatized.
Please @frivoal take a look, thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1153)
> [css-ui] Add new test to verify caret-color animation from JavaScript

- css-ui-3/caret-color-016.html
- css-ui-3/caret-color-017.html
Please @frivoal take a look. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1152)
> [css-ui] Add new tests for caret-color property

- LICENSE
- LICENSE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1158)
> Update License with text of dual licenses

- css21/pagination/page-break-margins-001.xht
line-height must be 1em for the 5 lines to appear in order.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/777)
> [css-page] Fix page-break-margins-001

- .travis.yml
Fixes #1140.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1167)
> Move Travis to Trusty, require build to complete again

- lint.whitelist
- manifest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1172)
> Add manifest script, update wpt_tools

- css-ui-3/text-overflow-005-ref.html
- css-ui-3/text-overflow-005.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1176)
> [css-ui-3] Add test for incremental text-overflow

- css-logical-properties-1/logicalprops-block-size-vlr.html
- css-logical-properties-1/logicalprops-block-size.html
- css-logical-properties-1/logicalprops-inline-size-vlr.html
- css-logical-properties-1/logicalprops-inline-size.html
- css-logical-properties-1/logicalprops-quirklength.html
- css-logical-properties-1/resources/style-check.js
Spec is here: https://drafts.csswg.org/css-logical-props-1/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1165)
> [css-logical-properties-1] Add test case for {inline-,block-}size

- css-display-3/display-flow-root-001-ref.html
- css-display-3/display-flow-root-001.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1179)
> Tests for display:flow-root

- css-transforms-1/transform-origin-013-ref.html
- css-transforms-1/transform-origin-013.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/989)
> Submit transform-origin-008.html.

- css-ui-3/text-overflow-005.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1185)
> [css-ui-3] Fix typo

- .travis.yml
(I'm not going to let Travis finish running this PR if it appears to work because it'll take hours.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1189)
> Get Travis building the testsuite again

- cssom-1/interfaces.html
This also includes a resources update to pick up the change from ArrayClass
to LegacyArrayClass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1195)
> Update the idlharness test for CSSOM.

- tools/build.py
- tools/travis/build.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1207)
> Stop jumping into pdb on errors.

- cssom-1/cssom-cssText-serialize.html
- cssom-1/cssstyledeclaration-csstext.html
- cssom-1/cssstylerule.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/964)
> Various cssom improvements.

- css-rhythm-1/line-height-step-writing-mode-vrl-001.html
- css-rhythm-1/line-height-step-writing-mode-vrl-ruby-001.html
- css-rhythm-1/reference/line-height-step-writing-mode-vrl-001.html
- css-rhythm-1/reference/line-height-step-writing-mode-vrl-ruby-001.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1211)
> [css-rhythm] Add vertical-rl test cases

- css-rhythm-1/line-height-step-ruby-001.html
- css-rhythm-1/reference/line-height-step-ruby-001.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1212)
> [css-rhythm] Add ruby test case

- build-css-testsuites.sh
- requirements.txt
cc/ @jgraham @plinss
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1214)
> Add a script to build the testsuite, virtualenv and all

- css-rhythm-1/line-height-step-writing-mode-vrl-001.html
- css-rhythm-1/line-height-step-writing-mode-vrl-ruby-001.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1216)
> [css-rhythm] Fix incorrect ref links

- css-animations-1/animation-common-ref.html
- css-animations-1/animation-delay-008.html
- css-animations-1/animation-delay-009.html
- css-animations-1/animation-delay-010.html
Based on:
https://github.com/w3c/csswg-drafts/commit/40af4c98fc172dc93fbbd4acc19b3b2b8550a345
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1027)
> [css-animations] Add tests for changes to animation-delay

- lint.whitelist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1222)
> Update wpt_tools, add new lints to whitelist

- geometry-1/DOMMatrix-003.html
Post-multiply a skew transformation on the current matrix.
https://drafts.fxtf.org/geometry/#dom-dommatrix-skewxself
https://drafts.fxtf.org/geometry/#dom-dommatrix-skewyself
https://www.w3.org/TR/css-transforms-1/#SkewDefined
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1243)
> [geometry-1] Post-multiply a skew transformation on the current matrix

- geometry-1/DOMMatrix-003.html
according to define of below specs, change expected matrices.
https://drafts.fxtf.org/geometry/#dom-dommatrix-translateself
https://drafts.fxtf.org/geometry/#dom-dommatrix-scaleself
https://www.w3.org/TR/css-transforms-1/#Translate3dDefined
https://www.w3.org/TR/css-transforms-1/#Scale3dDefined
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1244)
> [geometry-1] translate(), scale() without offsets tests is wrong.

- work-in-progress/adobe/css3-regions/regions-om-NamedFlow-001.html
- work-in-progress/adobe/css3-regions/regions-om-NamedFlow-002.html
- work-in-progress/adobe/css3-regions/regions-om-NamedFlow-003.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/990)
> Improve regions-om-NamedFlow tests.

- css-logical-props-1/cascading-001-ref.html
- css-logical-props-1/cascading-001.html
cc @emilio
r? @dbaron
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1145)
> [css-logical-props-1] Add test for cascading of logical and physical properties

- css-ui-3/box-sizing-026.html
- css-ui-3/box-sizing-027.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/csswg-test/1218)
> [css-ui-3] Add missing box-sizing tests
